# Generated by Django 5.1.3 on 2025-02-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('funcionario', models.CharField(max_length=255)),
            ],
        ),
    ]
